AllCops:
  TargetRubyVersion: 3.3.0
Metrics/MethodLength:
  Max: 25
  Enabled: true
Metrics/ClassLength:
  Max: 115
  Enabled: true
Metrics/AbcSize:
  Max: 44
  Enabled: true
Naming/MethodParameterName:
  Enabled: false
Layout/LineLength:
  Max: 125
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/ParameterLists:
  Max: 6
Metrics/PerceivedComplexity:
  Max: 14
Style/ConditionalAssignment:
  Enabled: false