AllCops:
  TargetRubyVersion: 3.3.0
Metrics/MethodLength:
  Max: 20
  Enabled: true
Metrics/ClassLength:
  Max: 115
  Enabled: true
Metrics/AbcSize:
  Max: 28
  Enabled: true
Naming/MethodParameterName:
  Enabled: false
