AllCops:
  TargetRubyVersion: 3.3.0
Metrics/MethodLength:
  Max: 50
  Enabled: true
Metrics/ClassLength:
  Max: 130
  Enabled: true
Metrics/AbcSize:
  Max: 58
  Enabled: true
Naming/MethodParameterName:
  Enabled: false
Layout/LineLength:
  Max: 125
Metrics/CyclomaticComplexity:
  Max: 17
Metrics/ParameterLists:
  Max: 6
Metrics/PerceivedComplexity:
  Max: 20
Style/ConditionalAssignment:
  Enabled: false
Style/NegativeCondition:
  Enabled: false
Style/UnlessElse:
  Enabled: false